
all: starforce-simov pb_rules olympica titan-strike starforce final-frontier

starforce-simov:
	cp starforce-simov.pdf ~/localdav/pdf
	xelatex starforce-simov

pb_rules:
	# Copy this over first because tex is broken at the moment
	cp pb_rules.pdf ~/localdav/pdf
	xelatex pb_rules

olympica:
	# Copy this over first because tex is broken at the moment
	cp olympica.pdf ~/localdav/pdf
	xelatex olympica

titan-strike:
	# Copy this over first because tex is broken at the moment
	cp titan-strike.pdf ~/localdav/pdf
	xelatex titan-strike

starforce:
	# Copy this over first because tex is broken at the moment
	cp starforce.pdf ~/localdav/pdf
	xelatex starforce

final-frontier:
	cp final-frontier.pdf ~/localdav/pdf
	xelatex final-frontier
